In [34]:
import pandas as pd



import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/zoo.csv")


In [6]:
data


animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
96      wallaby     1         0     0     1         0        0         0   
97         wasp     1         0     1     0         1        0         0   
98         wolf     1         0     0     1         0        0         1   
99         worm     0         0     1     0         0        0         0   
100        wren     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  class_type  
0          1           1  
1          1           1  
2          0           4  
3          1           1  
4          1           1  
..       ...         ...  
96         1           1  
97         0           6  
98         1           1  
99         0           7  
100        0           2  

[101 rows x 18 columns]

In [7]:
animal_name = data.drop('animal_name', axis=1)
panimal_name = data['animal_name']
print(animal_name)
print(panimal_name)

     hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0           1         1         0     0     4    

In [8]:
print(animal_name.head())

   hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  class_type  
0         1         0     0     4     0         0        1           1  
1         1         0     0     4     1         0        1           1  
2         0         0     1     0     1         0        0           4  
3         1         0     0     4     0         0        1           1  
4         1         0     0     4     1         0        1           1  


In [9]:
print(data.class_type)

0      1
1      1
2      4
3      1
4      1
      ..
96     1
97     6
98     1
99     7
100    2
Name: class_type, Length: 101, dtype: int64


In [13]:
X= animal_name.drop('class_type',axis=1)
y = data['class_type']
print(X)
print(y)

     hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0           1         1         0     0     4     

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [15]:
knn_classifier = KNeighborsClassifier(n_neighbors=19)

In [16]:
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=19)

In [17]:
y_pred = knn_classifier.predict(X_test)

In [18]:
class_type = pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
print(class_type)


    Actual  Predicted
84       1          1
55       1          1
66       1          4
67       1          1
45       1          1
39       6          7
22       1          1
44       1          1
10       1          1
0        1          1
18       4          4
30       6          7
97       6          7
33       2          2
77       7          4
4        1          1
93       1          1
78       2          2
12       4          4
31       1          1
76       3          4


In [19]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7142857142857143


In [20]:
import pickle

# Save the trained model to a file
with open('knn_model.pkl', 'wb') as file:
    pickle.dump(knn_classifier, file)

    print("Model saved successfully!")

Model saved successfully!


In [21]:
with open('knn_model.pkl', 'rb') as file:
      loaded_knn_classifier = pickle.load(file)

      print("Model loaded successfully!")



Model loaded successfully!


In [22]:
# Assuming you want to test on a sample from the test set
# Use .iloc to access the row by its index:
sample = X_test.iloc[0].values.reshape(1, -1)  # Reshape the sample to 2D

# Make prediction using the loaded model
sample_prediction = loaded_knn_classifier.predict(sample)

print("Prediction for the single sample:", sample_prediction)

# If you want to see the actual class label for comparison
# Use .iloc to access the corresponding label in y_test:
print("Actual label:", y_test.iloc[0])

Prediction for the single sample: [1]
Actual label: 1


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [23]:
# Example of a new sample input (replace these with your own values)
# The length of the list must match the number of features used in the model.
manual_sample = np.array([[5, 116, 74, 0, 0, 25.6, 0.201, 30]])



In [27]:
# Importing necessary libraries for Decision Tree Classifier and visualization
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import accuracy_score

# Load the dataset
data=pd.read_csv("/content/drive/MyDrive/zoo.csv") # Adjust the path as needed

# Preparing the data for the Decision Tree
# Dropping the 'animal_name' since it's not a useful feature for prediction
X = data.drop(columns=['animal_name', 'class_type'])
y = data['class_type']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Training the Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train)

# Predicting on the test set
y_pred = dt_classifier.predict(X_test)

# Calculating accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Displaying the decision tree in text form
decision_tree_rules = export_text(dt_classifier, feature_names=list(X.columns))
print("Decision Tree Rules:")
print(decision_tree_rules)


Accuracy: 95.24%
Decision Tree Rules:
|--- milk <= 0.50
|   |--- feathers <= 0.50
|   |   |--- fins <= 0.50
|   |   |   |--- backbone <= 0.50
|   |   |   |   |--- airborne <= 0.50
|   |   |   |   |   |--- predator <= 0.50
|   |   |   |   |   |   |--- legs <= 3.00
|   |   |   |   |   |   |   |--- class: 7
|   |   |   |   |   |   |--- legs >  3.00
|   |   |   |   |   |   |   |--- class: 6
|   |   |   |   |   |--- predator >  0.50
|   |   |   |   |   |   |--- class: 7
|   |   |   |   |--- airborne >  0.50
|   |   |   |   |   |--- class: 6
|   |   |   |--- backbone >  0.50
|   |   |   |   |--- aquatic <= 0.50
|   |   |   |   |   |--- class: 3
|   |   |   |   |--- aquatic >  0.50
|   |   |   |   |   |--- class: 5
|   |   |--- fins >  0.50
|   |   |   |--- class: 4
|   |--- feathers >  0.50
|   |   |--- class: 2
|--- milk >  0.50
|   |--- class: 1



In [38]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, mean_absolute_error, mean_squared_error, r2_score

# Preparing the data (same as before)
X = data.drop(columns=['animal_name', 'class_type'])
y = data['class_type']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Training the Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

# Predicting on the test set
y_pred = rf_classifier.predict(X_test)

# Calculating accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Calculating precision, recall, f1-score, and support
precision, recall, f1, support = precision_recall_fscore_support(y_test, y_pred, average='macro')
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")
print(f"Support: {support}")













# Feature importance
importances = rf_classifier.feature_importances_
features = X.columns
feature_importance = sorted(zip(importances, features), reverse=True)
print("Feature Importances:")
for importance, feature in feature_importance:
    print(f"{feature}: {importance:.4f}")


Accuracy: 95.24%
Precision: 0.78
Recall: 0.83
F1 Score: 0.80
Support: None
Feature Importances:
feathers: 0.1277
milk: 0.1243
eggs: 0.1022
legs: 0.1009
hair: 0.0961
toothed: 0.0834
backbone: 0.0725
breathes: 0.0706
fins: 0.0632
aquatic: 0.0439
tail: 0.0431
airborne: 0.0418
predator: 0.0140
catsize: 0.0097
venomous: 0.0061
domestic: 0.0007


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [30]:
# Naive Bayes classifier
naive_bayes_model = GaussianNB()
naive_bayes_model.fit(X_train, y_train)
y_pred_nb = naive_bayes_model.predict(X_test)
nb_accuracy = accuracy_score(y_test, y_pred_nb)
nb_class_report = classification_report(y_test, y_pred_nb)


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [31]:
print("Naive Bayes Classifier")
print("Accuracy:", nb_accuracy)
print("Classification Report:\n", nb_class_report)


Naive Bayes Classifier
Accuracy: 0.9523809523809523
Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         2
           3       0.00      0.00      0.00         1
           4       0.67      1.00      0.80         2
           6       1.00      1.00      1.00         3
           7       1.00      1.00      1.00         1

    accuracy                           0.95        21
   macro avg       0.78      0.83      0.80        21
weighted avg       0.92      0.95      0.93        21



In [35]:
logistic_model = LogisticRegression(max_iter=200)
logistic_model.fit(X_train, y_train)
y_pred_lr = logistic_model.predict(X_test)
lr_accuracy = accuracy_score(y_test, y_pred_lr)
lr_class_report = classification_report(y_test, y_pred_lr)

print("\nLogistic Regression Classifier")
print("Accuracy:", lr_accuracy)
print("Classification Report:\n", lr_class_report)


Logistic Regression Classifier
Accuracy: 0.9523809523809523
Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         2
           3       0.00      0.00      0.00         1
           4       0.67      1.00      0.80         2
           6       1.00      1.00      1.00         3
           7       1.00      1.00      1.00         1

    accuracy                           0.95        21
   macro avg       0.78      0.83      0.80        21
weighted avg       0.92      0.95      0.93        21



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [36]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

# Cross-validation for both models
nb_cv_scores = cross_val_score(naive_bayes_model, X, y, cv=5)
lr_cv_scores = cross_val_score(logistic_model, X, y, cv=5)

print("Naive Bayes Cross-Validation Accuracy:", nb_cv_scores.mean())
print("Logistic Regression Cross-Validation Accuracy:", lr_cv_scores.mean())

# Calculate precision, recall, F1 score for Logistic Regression predictions
print("Logistic Regression Precision:", precision_score(y_test, y_pred_lr, average='weighted'))
print("Logistic Regression Recall:", recall_score(y_test, y_pred_lr, average='weighted'))
print("Logistic Regression F1 Score:", f1_score(y_test, y_pred_lr, average='weighted'))
print("Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:776: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:776: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


Naive Bayes Cross-Validation Accuracy: 0.96
Logistic Regression Cross-Validation Accuracy: 0.95
Logistic Regression Precision: 0.9206349206349207
Logistic Regression Recall: 0.9523809523809523
Logistic Regression F1 Score: 0.9333333333333333
Logistic Regression Confusion Matrix:
 [[12  0  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  1]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [37]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

# Prepare the data
X = data.drop(columns=['animal_name', 'class_type'])
y = data['class_type']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Original Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train)
dt_y_pred = dt_classifier.predict(X_test)

# Tuned Decision Tree Classifier (with max_depth)
dt_classifier_tuned = DecisionTreeClassifier(max_depth=3, random_state=42)
dt_classifier_tuned.fit(X_train, y_train)
dt_y_pred_tuned = dt_classifier_tuned.predict(X_test)

# Evaluation for Original Decision Tree
print("Original Decision Tree Classifier:")
print(f"Accuracy: {accuracy_score(y_test, dt_y_pred):.2f}")
print("Classification Report:")
print(classification_report(y_test, dt_y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, dt_y_pred))

# Evaluation for Tuned Decision Tree
print("\nTuned Decision Tree Classifier (max_depth=3):")
print(f"Accuracy: {accuracy_score(y_test, dt_y_pred_tuned):.2f}")
print("Classification Report:")
print(classification_report(y_test, dt_y_pred_tuned))
print("Confusion Matrix:")
print(confusion_matrix(y_test, dt_y_pred_tuned))


Original Decision Tree Classifier:
Accuracy: 0.95
Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         2
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         2
           5       0.00      0.00      0.00         0
           6       1.00      1.00      1.00         3
           7       1.00      1.00      1.00         1

    accuracy                           0.95        21
   macro avg       0.71      0.71      0.71        21
weighted avg       0.95      0.95      0.95        21

Confusion Matrix:
[[12  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  1]]

Tuned Decision Tree Classifier (max_depth=3):
Accuracy: 0.81
Classification Report:
              precision    recall  f1-score   support

   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_